# Generated by Django 4.2.21 on 2025-05-11 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='ciudad',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='ciudad.ciudad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
