# Generated by Django 4.2.21 on 2025-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_negocio_ciudad_alter_negocio_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
