# Generated by Django 4.2.21 on 2025-05-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_alter_negocio_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='fotos',
            field=models.CharField(blank=True, default=list),
        ),
    ]
