# Generated by Django 5.2.1 on 2025-05-16 18:18

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0004_alter_negocio_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.get_upload_path),
        ),
    ]
