# Generated by Django 5.2.1 on 2025-05-16 21:59

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_negocio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.get_upload_path),
        ),
    ]
