# Generated by Django 4.2.21 on 2025-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio_fecha_actualizacion_servicio_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
