# Generated by Django 5.2.1 on 2025-05-16 18:18

import apps.core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_servicio_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id_imagen', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to=apps.core.utils.get_upload_path)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicio.servicio')),
            ],
            options={
                'db_table': 'imagenes_servicio',
                'ordering': ['orden'],
            },
        ),
    ]
