# Generated by Django 4.2.21 on 2025-05-11 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0002_negocio_ciudad_alter_negocio_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenNegocio',
            fields=[
                ('id_imagen', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField()),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio')),
            ],
            options={
                'db_table': 'imagenes_negocio',
            },
        ),
    ]
