# Generated by Django 5.2.1 on 2025-05-16 18:18

import apps.imagenes_negocio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes_negocio', '0002_alter_imagennegocio_fecha_subida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagennegocio',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='imagennegocio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.imagenes_negocio.models.upload_to),
        ),
    ]
