# Generated by Django 4.2.21 on 2025-05-11 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0002_negocio_ciudad_alter_negocio_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_contratacion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
