# Generated by Django 5.2.1 on 2025-05-16 18:18

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.get_upload_path),
        ),
    ]
