# Generated by Django 5.2.1 on 2025-05-16 18:18

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.get_upload_path),
        ),
    ]
