# Generated by Django 4.2.21 on 2025-05-10 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        ('usuario', '0001_initial'),
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id_resenia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cita_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cita.cita')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio')),
            ],
            options={
                'db_table': 'resenia',
            },
        ),
    ]
