# Generated by Django 4.2.21 on 2025-05-11 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resenia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
