# Generated by Django 4.2.21 on 2025-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenia', '0002_alter_resenia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
