# Generated by Django 4.2.21 on 2025-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_cita_empleado_alter_cita_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
