# Generated by Django 5.2.1 on 2025-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_alter_cita_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
