# Generated by Django 5.2.1 on 2025-05-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_alter_cita_fecha_creacion'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
    ]
