# Generated by Django 5.2.1 on 2025-05-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_alter_categoria_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
