# Generated by Django 4.2.21 on 2025-05-11 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodos_pago', '0001_initial'),
        ('cita', '0002_cita_empleado_alter_cita_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('reembolsado', 'Reembolsado')], max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
                ('id_metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metodos_pago.metodopago')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
