# Generated by Django 4.2.21 on 2025-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
